version: '3'

services:
  exporter:
    image: http-scrap
    build:
      context: .
    environment:
    - DELAY=5
    - CONFIG=config.yaml
    volumes:
    -  ./config-local.yaml:/app/config.yaml
    # entrypoint: []
    # command: []
    # ports: ["from:to"]
    # volumes: ["local:container"]