version: '3'

services:
  exporter:
    image: http-exporter
    build:
      context: .
    environment:
      - DELAY=5
      - CONFIG=config.yaml
    # entrypoint: []
    # command: []
    # ports: ["from:to"]
    # volumes: ["local:container"]